name: weathe_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  geolocator: ^10.1.0
  cloud_firestore: ^4.13.2
  flutter_bloc: ^8.1.3
  firebase_core: ^2.23.0
  lottie: ^2.7.0
  flutter_native_splash: ^2.3.6
  google_fonts: ^6.1.0
  intl: ^0.18.1
  fl_chart: ^0.65.0
  country_picker: ^2.0.23
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter_native_splash:

  color: "#202046" #   "#6699cc66" #Colors.blue.withOpacity(0.4)
  image: assets/images/splash_img_nobg.png
  branding: assets/images/logo.png #only png supported(not working currently)
 # color_dark: "#444444" #dark grey
  image_dark: assets/images/splash_img_nobg.png   #to do : add dark image 
#  branding_dark: assets/images/logo.png #only png supported
  fullscreen: true

  android_12:
    image: assets/images/splash_img_nobg.png       #assets/images/cloud.png
    icon_background_color: "#202046"
    image_dark: assets/images/splash_img_nobg.png
    icon_background_color_dark: "#202046"
    fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/images/weather_icons/


  
